### ISSUE TITLE
How to use the first way to install?

### ISSUE THREAD

**Issue by Wilson1211** [lantw44/ceiba-dl#12]
Autoconf，用於產生 configure 。

Automake，用於產生 Makefile.in 。

Autoconf Archive， 需要 AX_PYTHON_MODULE 和 AX_COMPILER_FLAGS。

How to use Autoconf to generate configure file? And so does Makefile.in and the last one.

which file to edit my account and password for Ceiba system?

**Comment by lantw44** [comment]
> How to use Autoconf to generate configure file? And so does Makefile.in and the last one.

Just run the `autogen.sh` script. It will run `autoreconf` for you, and `autoreconf` knows how to execute autoconf and automake commands in the correct order to generate all necessary files.

> which file to edit my account and password for Ceiba system?

Run `ceiba-dl login` and follow its instruction. This program does not need your CEIBA account and password. Instead, it uses the session cookie which is generated by the server during logging in on the web page.

**Comment by Wilson1211** [comment]
it shows the following error message


./autogen.sh
*** WARNING: I am going to run `configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** `./autogen.sh' command line.

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:25: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

**Comment by lantw44** [comment]
> autoreconf: running: /usr/bin/autoconf --force
> configure.ac:25: error: possibly undefined macro: AC_MSG_ERROR

`AC_MSG_ERROR` is a builtin macro of autoconf, so it should never be missing.

```autoconf
18 AC_PROG_CC
19 AC_PROG_CC_STDC
20 AM_PATH_PYTHON([3])
21 case "$PYTHON" in
22     /*)
23         ;;
24     *)
25         AC_MSG_ERROR([The path to python interpreter must be absolute])
26         ;;
27 esac
28 AX_PYTHON_MODULE([lxml], [1])
29 AX_PYTHON_MODULE([pycurl], [1])
30 AX_PYTHON_MODULE([xdg], [1])
```

There are `AM_PATH_PYTHON` calls above and `AX_PYTHON_MODULE` calls below. `AC` means autoconf, `AM` means automake, and `AX` means autoconf-archive. Are you sure that all of them are installed?

**Comment by Wilson1211** [comment]
The following links solved my problem. It turns out that I miss some packages.

https://superuser.com/questions/565988/autoconf-libtool-and-an-undefined-ac-prog-libtool
https://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error
